import { DesignTemplate } from '../types';

export const STARTER_TEMPLATES: DesignTemplate[] = [
  {
    id: 'template-realty-card',
    name: 'Luxe Real Estate Agent',
    category: 'Real Estate',
    productType: 'business-cards',
    previewUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=400&q=80',
    tags: ['luxury', 'real estate', 'professional', 'corporate'],
    elements: {
      front: [
        {
          id: 'bg-bar',
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 320,
          height: 180,
          rotation: 0,
          fillColor: '#0f172a',
          strokeColor: '#0f172a',
          strokeWidth: 0,
          borderRadius: 0,
        },
        {
          id: 'accent-gold',
          type: 'shape',
          shapeType: 'line',
          x: 20,
          y: 110,
          width: 80,
          height: 3,
          rotation: 0,
          fillColor: '#f59e0b',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
        },
        {
          id: 'brand-name',
          type: 'text',
          text: 'ELEVATE',
          fontFamily: 'Montserrat',
          fontSize: 22,
          fontWeight: '900',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#f8fafc',
          letterSpacing: 4,
          x: 20,
          y: 25,
          width: 200,
          height: 30,
          rotation: 0,
        },
        {
          id: 'brand-sub',
          type: 'text',
          text: 'PREMIER REAL ESTATE GROUP',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 8,
          fontWeight: '600',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#94a3b8',
          letterSpacing: 2,
          x: 20,
          y: 55,
          width: 220,
          height: 15,
          rotation: 0,
        },
        {
          id: 'agent-name',
          type: 'text',
          text: 'Marcus Vance',
          fontFamily: 'Playfair Display',
          fontSize: 16,
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#fbbf24',
          x: 20,
          y: 85,
          width: 180,
          height: 22,
          rotation: 0,
        },
        {
          id: 'agent-title',
          type: 'text',
          text: 'Senior Broker Associate • Lic #849201',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 8,
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#cbd5e1',
          x: 20,
          y: 120,
          width: 200,
          height: 14,
          rotation: 0,
        },
        {
          id: 'agent-contact',
          type: 'text',
          text: '📞 (555) 234-8900\n✉️ marcus@elevaterealty.com\n🌐 www.elevaterealty.com',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 7.5,
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#94a3b8',
          lineHeight: 1.4,
          x: 20,
          y: 135,
          width: 220,
          height: 40,
          rotation: 0,
        },
        {
          id: 'qr-code',
          type: 'qr',
          data: 'https://elevaterealty.com/marcus',
          color: '#0f172a',
          bgColor: '#ffffff',
          x: 235,
          y: 85,
          width: 65,
          height: 65,
          rotation: 0,
        }
      ],
      back: [
        {
          id: 'bg-back',
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 320,
          height: 180,
          rotation: 0,
          fillColor: '#020617',
          strokeColor: '#020617',
          strokeWidth: 0,
        },
        {
          id: 'back-logo',
          type: 'text',
          text: 'ELEVATE',
          fontFamily: 'Montserrat',
          fontSize: 32,
          fontWeight: '900',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#fbbf24',
          letterSpacing: 6,
          x: 10,
          y: 60,
          width: 300,
          height: 40,
          rotation: 0,
        },
        {
          id: 'back-tagline',
          type: 'text',
          text: 'UNMATCHED LUXURY LIVING',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 9,
          fontWeight: '600',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#94a3b8',
          letterSpacing: 3,
          x: 10,
          y: 105,
          width: 300,
          height: 20,
          rotation: 0,
        }
      ]
    }
  },
  {
    id: 'template-tech-startup',
    name: 'Modern Tech & SaaS',
    category: 'Technology',
    productType: 'business-cards',
    previewUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=400&q=80',
    tags: ['tech', 'startup', 'minimal', 'modern', 'gradient'],
    elements: {
      front: [
        {
          id: 'tech-bg',
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 320,
          height: 180,
          rotation: 0,
          fillColor: '#ffffff',
          strokeColor: '#f1f5f9',
          strokeWidth: 1,
        },
        {
          id: 'top-pill',
          type: 'shape',
          shapeType: 'badge',
          x: 20,
          y: 20,
          width: 40,
          height: 40,
          rotation: 0,
          fillColor: '#4f46e5',
          strokeColor: '#4338ca',
          strokeWidth: 0,
        },
        {
          id: 'co-name',
          type: 'text',
          text: 'Synthetix AI',
          fontFamily: 'Montserrat',
          fontSize: 18,
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#0f172a',
          letterSpacing: 0.5,
          x: 70,
          y: 25,
          width: 200,
          height: 25,
          rotation: 0,
        },
        {
          id: 'co-tagline',
          type: 'text',
          text: 'Enterprise Neural Automation',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 8,
          fontWeight: '500',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#6366f1',
          x: 70,
          y: 48,
          width: 200,
          height: 15,
          rotation: 0,
        },
        {
          id: 'usr-name',
          type: 'text',
          text: 'Dr. Elena Rostova',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 14,
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#1e293b',
          x: 20,
          y: 90,
          width: 200,
          height: 20,
          rotation: 0,
        },
        {
          id: 'usr-role',
          type: 'text',
          text: 'Founder & Chief Research Scientist',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 8.5,
          fontWeight: '500',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#64748b',
          x: 20,
          y: 112,
          width: 220,
          height: 16,
          rotation: 0,
        },
        {
          id: 'usr-info',
          type: 'text',
          text: 'elena@synthetix.ai  •  synthetix.ai  •  San Francisco, CA',
          fontFamily: 'Roboto Mono',
          fontSize: 7.5,
          fontWeight: '400',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          color: '#475569',
          x: 20,
          y: 145,
          width: 280,
          height: 18,
          rotation: 0,
        }
      ]
    }
  },
  {
    id: 'template-artisan-coffee',
    name: 'Artisan Cafe & Roastery',
    category: 'Food & Beverage',
    productType: 'homeware',
    previewUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
    tags: ['coffee', 'cafe', 'artisan', 'mug', 'vintage'],
    elements: {
      front: [
        {
          id: 'circle-badge',
          type: 'shape',
          shapeType: 'circle',
          x: 75,
          y: 20,
          width: 150,
          height: 150,
          rotation: 0,
          fillColor: '#fffbeb',
          strokeColor: '#78350f',
          strokeWidth: 3,
        },
        {
          id: 'coffee-title',
          type: 'text',
          text: 'ROAST & RHYTHM',
          fontFamily: 'Oswald',
          fontSize: 16,
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#78350f',
          letterSpacing: 2,
          x: 80,
          y: 65,
          width: 140,
          height: 25,
          rotation: 0,
        },
        {
          id: 'coffee-sub',
          type: 'text',
          text: 'SMALL BATCH CRAFT COFFEE',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 7,
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#b45309',
          letterSpacing: 1.5,
          x: 80,
          y: 92,
          width: 140,
          height: 15,
          rotation: 0,
        },
        {
          id: 'coffee-est',
          type: 'text',
          text: 'EST. 2018 • BROOKLYN, NY',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 6.5,
          fontWeight: '600',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#92400e',
          x: 80,
          y: 115,
          width: 140,
          height: 15,
          rotation: 0,
        }
      ]
    }
  },
  {
    id: 'template-streetwear-tee',
    name: 'Cyberpunk Apparel Graphic',
    category: 'Fashion & Streetwear',
    productType: 'apparel',
    previewUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
    tags: ['streetwear', 'fashion', 't-shirt', 'graphic', 'bold'],
    elements: {
      front: [
        {
          id: 'tee-graphic-box',
          type: 'shape',
          shapeType: 'rectangle',
          x: 35,
          y: 30,
          width: 230,
          height: 180,
          rotation: 0,
          fillColor: '#18181b',
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          borderRadius: 8,
        },
        {
          id: 'tee-title',
          type: 'text',
          text: 'NEO TOKYO',
          fontFamily: 'Montserrat',
          fontSize: 26,
          fontWeight: '900',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#38bdf8',
          letterSpacing: 5,
          x: 40,
          y: 60,
          width: 220,
          height: 35,
          rotation: 0,
        },
        {
          id: 'tee-sub',
          type: 'text',
          text: 'SYSTEM OVERLOAD // 2099',
          fontFamily: 'Roboto Mono',
          fontSize: 10,
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#f43f5e',
          letterSpacing: 2,
          x: 40,
          y: 105,
          width: 220,
          height: 20,
          rotation: 0,
        },
        {
          id: 'tee-tag',
          type: 'text',
          text: 'OFFLINE SENSORY ARCHIVE • ALL RIGHTS RESERVED',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 6.5,
          fontWeight: '600',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#a1a1aa',
          letterSpacing: 1,
          x: 40,
          y: 155,
          width: 220,
          height: 20,
          rotation: 0,
        }
      ]
    }
  },
  {
    id: 'template-grand-opening-flyer',
    name: 'Grand Opening Event Flyer',
    category: 'Events & Promotions',
    productType: 'marketing',
    previewUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=400&q=80',
    tags: ['flyer', 'promotion', 'sale', 'event', 'party'],
    elements: {
      front: [
        {
          id: 'flyer-bg',
          type: 'shape',
          shapeType: 'rectangle',
          x: 0,
          y: 0,
          width: 280,
          height: 360,
          rotation: 0,
          fillColor: '#4f46e5',
          strokeColor: '#4f46e5',
          strokeWidth: 0,
        },
        {
          id: 'flyer-banner',
          type: 'text',
          text: 'YOU ARE INVITED',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 11,
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#fef08a',
          letterSpacing: 3,
          x: 20,
          y: 35,
          width: 240,
          height: 20,
          rotation: 0,
        },
        {
          id: 'flyer-title',
          type: 'text',
          text: 'GRAND\nOPENING',
          fontFamily: 'Montserrat',
          fontSize: 34,
          fontWeight: '900',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#ffffff',
          lineHeight: 1.1,
          letterSpacing: 2,
          x: 20,
          y: 70,
          width: 240,
          height: 80,
          rotation: 0,
        },
        {
          id: 'flyer-deal-box',
          type: 'shape',
          shapeType: 'rectangle',
          x: 35,
          y: 170,
          width: 210,
          height: 60,
          rotation: 0,
          fillColor: '#fbbf24',
          strokeColor: '#f59e0b',
          strokeWidth: 0,
          borderRadius: 8,
        },
        {
          id: 'flyer-deal-text',
          type: 'text',
          text: 'FIRST 100 GUESTS GET\n50% OFF EVERYTHING',
          fontFamily: 'Montserrat',
          fontSize: 12,
          fontWeight: '800',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#1e1b4b',
          x: 40,
          y: 180,
          width: 200,
          height: 40,
          rotation: 0,
        },
        {
          id: 'flyer-details',
          type: 'text',
          text: 'SATURDAY, OCTOBER 24 • 10:00 AM\n742 Evergreen Terrace, Suite 400\nFree Drinks & Live DJ',
          fontFamily: 'Plus Jakarta Sans',
          fontSize: 9,
          fontWeight: '600',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#e0e7ff',
          lineHeight: 1.4,
          x: 20,
          y: 250,
          width: 240,
          height: 50,
          rotation: 0,
        },
        {
          id: 'flyer-rsvp',
          type: 'text',
          text: 'RSVP: WWW.EVENTSPARK.COM',
          fontFamily: 'Roboto Mono',
          fontSize: 9,
          fontWeight: '700',
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          color: '#fef08a',
          letterSpacing: 1,
          x: 20,
          y: 315,
          width: 240,
          height: 20,
          rotation: 0,
        }
      ]
    }
  }
];
